### PR TITLE
Rename profiler.inc to samp_profiler.inc (#33)

### PR DESCRIPTION
**Pull request by Fairuz-Afdhal**

### CODE REVIEW

**Comment by Fairuz-Afdhal** [comment]
@Zeex why? The issue is still exists especially for sampctl users, they have to delete/rename profiler.inc to something else and I feel like this is the appropriate name for the include.

**Comment by Zeex** [comment]
IMO it's something that should be addressed by sampctl

**Comment by ADRFranklin** [comment]
This is not a sampctl issue, the same issue would happen without sampctl, remember sampctl is just calling the pawncc with include paths, however because of the behaviour of pawncc when 2 files with the same name can be included from the include path directly, sampctl will throw an error about this problem, just to make the user aware, since there is no way to tell which include the pawncc will choose to use when you include it.

There isn't really a good solution for this, other then renaming the files. I'm open to suggestions that sampctl could do to help mitigate this issue, but once again this shouldn't be a sampctl problem.

**Comment by ADRFranklin** [comment]
We have already had this conversation here a while back: https://github.com/Zeex/samp-plugin-profiler/issues/33

**Pull request closed without merging**
